# Generated by Django 5.2.7 on 2025-10-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=50)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('contract_url', models.URLField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('first_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('maintenance_type', models.CharField(max_length=20)),
                ('request_status', models.CharField(default='Pending', max_length=20)),
                ('other_description', models.TextField(blank=True, default='')),
                ('description', models.TextField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tenant')),
            ],
        ),
    ]
