# Generated by Django 5.2.7 on 2025-10-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
