# Generated by Django 5.2.7 on 2025-10-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('landlord_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='assigned_landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='landlord_login.landlordprofile'),
        ),
    ]
