# Generated by Django 5.2.7 on 2025-10-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tenant_activation_code_tenant_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='activation_code',
        ),
        migrations.AddField(
            model_name='tenant',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
